name: peter
version: 0.1.0.0
github: "antonkesy/peter-lang"
license: Apache-2.0
author: "Anton Kesy"
maintainer: "antonkesy@gmail.com"
copyright: "2024 Anton Kesy"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: Please see the README on GitHub at <https://github.com/antonkesy/peter-lang#readme>

dependencies:
  - base >= 4.7 && < 5
  - parsec >= 3.1.16 && < 4
  - prettyprinter >= 1.7.1 && < 2
  - optparse-applicative >= 0.17.0
  - containers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  peter-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - peter

tests:
  peter-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - peter
      - HUnit
