name: build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: build and pre-commit
        uses: docker/build-push-action@v5
        with:
          context: .
